### ISSUE TITLE
Pokemon Sidekick Wallpaper seems to be the only live wallpaper going haywire

### ISSUE THREAD

**Issue by Thisisauser6443** [Kingsman44/Pixelify#117]
**Device** - Google Pixel 4a 5G
**ROM** - Stock Android 13/T/SDK 33 (August 2022 Patch; Likely to continue onto the September 2022 Patch)
**Magisk Build** - Canary 38ab6858
**Pixelify MM Build** - 2.02

Recently had some issue with the sidekick wallpaper, in the fact that it would either:
1. Fail to render in a preview, inside the 'Wallpaper and style' app
2. Render incorrectly with a broken-looking liquefied fallback wallpaper

Haven't got a logcat, unfortunately, since I'm not sure how to get one, exactly

**Comment by Kingsman44** [comment]
Can record the video for it?
also try v2.1 first

**Comment by Thisisauser6443** [comment]
Liquid fallback
![Screenshot_20220911-115306.png](https://user-images.githubusercontent.com/75092921/189523712-fa6da128-f4f5-4564-a4dc-5760d97b67f6.png)

Failed rendering of the actual wallpaper
![Screenshot_20220911-115950.png](https://user-images.githubusercontent.com/75092921/189523910-a862ad0b-3f7c-4ad2-a9b5-b6054820d6a0.png)

I've tried updating the module, but it hasn't worked, for me. Gonna do a clean install, and see how that works

**Comment by Thisisauser6443** [comment]
I've pulled out the error log for this. Not sure if it's worth much, but I'd thought I'd share, anyway

```
================================================================ Generated by AppErrorsTracking Project Url: https://github.com/KitsunePie/AppErrorsTracking ================================================================ [Device Brand]: google [Device Model]: Pixel 4a (5G) [Display]: TP1A.221105.002 [Android Version]: 13 [API Version]: 33 [System Locale]: en_GB [Package Name]: com.google.pixel.livewallpaper [Error Type]: Jvm [Crash Time]: 2022-11-23T08:25:45.165 [Stack Trace]: java.lang.Error: FATAL EXCEPTION [UnityMain] Unity version : 2019.3.0b8 Device model : Google Pixel 6 Pro Device fingerprint: google/raven/raven:13/TP1A.220624.021/8877034:user/release-keys Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** Version '2019.3.0b8 (7eb5456f98b4)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a' Build fingerprint: 'google/bramble/bramble:13/TP1A.221105.002/9080065:user/release-keys' Revision: 'MP1.0' ABI: 'arm64' Timestamp: 2022-11-23 08:25:43+0000 pid: 6092, tid: 17483, name: UnityMain >>> com.google.pixel.livewallpaper:pokemonwallpaper <<< uid: 10496 signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4a Cause: null pointer dereference x0 0000000000000000 x1 0000000000000000 x2 00000075346409b0 x3 0000007534640ae0 x4 0000000000000000 x5 000000746000041a x6 676e457974696e55 x7 65726f432e656e69 x8 00000074ca817fe4 x9 df65d3f8ca5f9a23 x10 0000000000000018 x11 0000000000000015 x12 000000001c386a3a x13 000000006c73beac x14 000000000000006c x15 00000000c07e3c78 x16 00000074cd0ee1e0 x17 00000077e5d1b7e0 x18 00000000e843421b x19 0000007534640ae0 x20 0000000000000000 x21 0000000000000000 x22 00000075346409b0 x23 0000000000000000 x24 0000000000000000 x25 0000000000000042 x26 00000074cd1654a8 x27 00000074cd1654a0 x28 00000074cd165310 x29 00000074ca817d64 sp 0000007534640920 lr 00000074cc4e7d50 pc 00000074ca840d28 backtrace: #00 pc 00000000003f3d28 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: fbdd4be9db2e6af149d6a25b8006272cf4515adc) #01 pc 00000000002e3d4c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #02 pc 00000000002f1394 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #03 pc 000000000071de7c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #04 pc 00000000002f0f18 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #05 pc 00000000002f0d9c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #06 pc 0000000000339020 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #07 pc 0000000000338ee4 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #08 pc 0000000000338e48 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #09 pc 000000000032aea0 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #10 pc 000000000032b4bc /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #11 pc 000000000032b918 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #12 pc 00000000000cfd7c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #13 pc 00000000001b4a44 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #14 pc 00000000001b4b10 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #15 pc 000000000025cd2c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #16 pc 0000000000356e9c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #17 pc 0000000000357808 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #18 pc 000000000036999c /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/split_pokemon.config.arm64_v8a.apk (BuildId: 8c8c9600e6f15cf4f7be830e726acdd1e39fcce6) #19 pc 000000000001cf14 /data/app/~~Rtz2f2Zx5leStTTXPMi-_A==/com.google.pixel.livewallpaper-Fh5lXtlPpa7KMfMXrmYESA==/oat/arm64/base.odex 	at split_pokemon.0x3f3d28(Native Method) 	at split_pokemon.0x2e3d4c(Native Method) 	at split_pokemon.0x2f1394(Native Method) 	at split_pokemon.0x71de7c(Native Method) 	at split_pokemon.0x2f0f18(Native Method) 	at split_pokemon.0x2f0d9c(Native Method) 	at split_pokemon.0x339020(Native Method) 	at split_pokemon.0x338ee4(Native Method) 	at split_pokemon.0x338e48(Native Method) 	at split_pokemon.0x32aea0(Native Method) 	at split_pokemon.0x32b4bc(Native Method) 	at split_pokemon.0x32b918(Native Method) 	at split_pokemon.0xcfd7c(Native Method) 	at split_pokemon.0x1b4a44(Native Method) 	at split_pokemon.0x1b4b10(Native Method) 	at split_pokemon.0x25cd2c(Native Method) 	at split_pokemon.0x356e9c(Native Method) 	at split_pokemon.0x357808(Native Method) 	at split_pokemon.0x36999c(Native Method) 	at base.0x1cf14(Native Method)
```

**Comment by Thisisauser6443** [comment]
[com.google.pixel.livewallpaper_2022-11-23T08_25_45.165.txt](https://github.com/Kingsman44/Pixelify/files/10086861/com.google.pixel.livewallpaper_2022-11-23T08_25_45.165.txt)

Error log I generated using another Xposed module. Not sure if this can help, but I can still reproduce it, with the exact same results, so maybe this would be worth a shot?
