### ISSUE TITLE
Pixel Launcher Crashes ArrowOs 12 GApps

### ISSUE THREAD

**Issue by OliverRhyme** [Kingsman44/Pixelify#81]
Pixel launcher always crashes on official arrow os 12 gapps (poco x3 nfc).

It crashes with this

```
FATAL EXCEPTION: launcher-loader
Process: com.google.android.apps.nexuslauncher, PID: 24717
java.lang.SecurityException: Permission Denial: createPredictionSession from pid=24717, uid=10175 expected caller to hold PACKAGE_USAGE_STATS permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.prediction.IPredictionManager$Stub$Proxy.createPredictionSession(IPredictionManager.java:329)
	at android.app.prediction.AppPredictor.<init>(AppPredictor.java:102)
	at android.app.prediction.AppPredictionManager.createAppPredictionSession(AppPredictionManager.java:47)
	at com.android.launcher3.model.QuickstepModelDelegate.recreatePredictors(SourceFile:9)
	at com.android.launcher3.model.QuickstepModelDelegate.workspaceLoadComplete(SourceFile:2)
	at com.google.android.apps.nexuslauncher.model.NexusLauncherModelDelegate.workspaceLoadComplete(SourceFile:1)
	at com.android.launcher3.model.LoaderTask.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Kingsman44** [comment]
it is because, asking permission is not prsent on stock pixel launcher, i will add it soon...

**Comment by OliverRhyme** [comment]
Any workarounds with this? Maybe via adb?

**Comment by tomikonio** [comment]
Hi,
Pixel launcher crashes as well, the recently menu is unusable.
Miui 13, android 12.
```
java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1
	at android.content.res.TypedArray.getColor(TypedArray.java:537)
	at com.android.launcher3.icons.GraphicsUtils.getAttrColor(SourceFile:2)
	at com.android.launcher3.util.Themes.getAttrColor(SourceFile:1)
	at J1.B.Z(SourceFile:4)
	at J1.B.initOverlay(SourceFile:47)
	at com.android.quickstep.views.TaskThumbnailView.refreshOverlay(SourceFile:4)
	at com.android.quickstep.views.TaskThumbnailView.setOverlayEnabled(SourceFile:3)
	at com.android.quickstep.views.TaskView.setOverlayEnabled(SourceFile:1)
	at com.android.quickstep.views.RecentsView.updateEnabledOverlays(SourceFile:4)
	at com.android.quickstep.views.RecentsView.notifyPageSwitchListener(SourceFile:3)
	at com.android.launcher3.PagedView.setCurrentPage(SourceFile:8)
	at com.android.launcher3.PagedView.setCurrentPage(SourceFile:1)
	at com.android.launcher3.PagedView.onLayout(SourceFile:14)
	at com.android.quickstep.views.RecentsView.onLayout(SourceFile:1)
	at com.android.quickstep.views.RecentsView$15.onEnd(SourceFile:24)
	at com.android.quickstep.views.RecentsView$15.accept(SourceFile:5)
	at com.android.quickstep.views.RecentsView$15.accept(SourceFile:1)
	at com.android.launcher3.anim.AnimatorListeners$EndStateCallbackWrapper.onAnimationEnd(SourceFile:5)
	at P0.c.accept(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.lambda$callListenerCommandRecursively$2(SourceFile:2)
	at com.android.launcher3.anim.AnimatorPlaybackController.a(Unknown Source:0)
	at t0.e.accept(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(SourceFile:1)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(SourceFile:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.callListenerCommandRecursively(SourceFile:1)
	at com.android.launcher3.anim.AnimatorPlaybackController.dispatchOnEnd(SourceFile:1)
	at com.android.launcher3.anim.AnimatorPlaybackController$OnAnimationEndDispatcher.onAnimationSuccess(SourceFile:2)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(SourceFile:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:870)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by ziddey** [comment]
Seeing the same with a moto edge 2021 on android 12. Disabling "Overview suggestions" fixes it.
