### ISSUE TITLE
[Bug] Error when trying to select Pokemon live wallpaper

### ISSUE THREAD

**Issue by cehnemdark** [Kingsman44/Pixelify#83]
On > Pixelify-v2.02-beta-3.1
https://paste.crdroid.net/ZhLr87

time: 1650457694579
msg: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmain.so" not found
stacktrace: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2019.3.0b8
Device model      : Google Pixel 6 Pro
Device fingerprint: google/raven/raven:12/SQ1D.220205.003/8069835:user/release-keys

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmain.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at com.unity3d.player.UnityPlayer.<clinit>(Unknown Source:10)
	at cyy.a(SourceFile:33)
	at com.google.unity.livewallpaper.GWallpaperService$a.onCreate(SourceFile:137)
	at android.service.wallpaper.WallpaperService$Engine.attach(WallpaperService.java:1316)
	at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:2162)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Kingsman44** [comment]
does your rom already provides Live wallpapers?

anyway, it was crashing due to conflict in apk or playstore had given wrong update.
i will be updating Livewallpaper to latest version from myside will fix this also.

**Comment by Kingsman44** [comment]
This is fixed, if still facing some issues feel free to reopen this issue
