### ISSUE TITLE
pixelify module causes non-stop logcat error/warnings spam

### ISSUE THREAD

**Issue by soredake** [Kingsman44/Pixelify#94]
Example of the spam:
```
[05-17 12:16:18.541 6451:6702 W/ziparchive]
Unable to open '/system/product/overlay/Pixelify.apk': No such file or directory

[05-17 12:16:18.541 6451:6702 E/.gms.persisten]
Failed to open APK '/system/product/overlay/Pixelify.apk': I/O error

[05-17 12:16:18.541 6451:6702 W/ResourcesManager]
failed to preload asset path '/system/product/overlay/Pixelify.apk'
java.io.IOException: Failed to load asset path /data/resource-cache/system@product@overlay@Pixelify.apk@idmap
	at android.content.res.ApkAssets.nativeLoad(Native Method)
	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
	at android.content.res.ApkAssets.loadOverlayFromPath(ApkAssets.java:215)
	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:452)
	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:980)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1101)
	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2415)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1793)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1779)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1807)
	at ciss.a(:com.google.android.gms@221514044@22.15.14 (190400-441847897):6)
	at btdn.c(:com.google.android.gms@221514044@22.15.14 (190400-441847897):34)
	at aztk.e(:com.google.android.gms@221514044@22.15.14 (190400-441847897):33)
	at aztk.c(:com.google.android.gms@221514044@22.15.14 (190400-441847897):28)
	at aztk.b(:com.google.android.gms@221514044@22.15.14 (190400-441847897):4)
	at aztb.g(:com.google.android.gms@221514044@22.15.14 (190400-441847897):4)
	at azrz.e(:com.google.android.gms@221514044@22.15.14 (190400-441847897):4)
	at azrz.f(:com.google.android.gms@221514044@22.15.14 (190400-441847897):2)
	at afrk.em(:com.google.android.gms@221514044@22.15.14 (190400-441847897):1)
	at afrq.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):11)
	at ccff.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):2)
	at wll.c(:com.google.android.gms@221514044@22.15.14 (190400-441847897):6)
	at wll.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at wqp.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
	at java.lang.Thread.run(Thread.java:1013)

[05-17 12:16:18.541 6451:6702 W/ziparchive]
Unable to open '/system/product/overlay/PixelifyFilpendo.apk': No such file or directory
```

Sample logcat spam:
[logcat_05-17-2022_12-19-21.zip](https://github.com/Kingsman44/Pixelify/files/8706990/logcat_05-17-2022_12-19-21.zip)

My ROM is crdroid 8.4 on whyred

**Comment by Kingsman44** [comment]
Plz ignore, it can't be solved. magisk doesn't inject files to system but stores on /data/adb/modules. might be the reason you get this.
