### ISSUE TITLE
Wallpapers and styles crashing 

### ISSUE THREAD

**Issue by igorkietrz** [Kingsman44/Pixelify#99]
Model: Galaxy A71
OS: Android 12 (One UI 4.1)

**Comment by Kingsman44** [comment]
can u send crash logs?

**Comment by igorkietrz** [comment]
> can u send crash logs?

Logcat?

**Comment by igorkietrz** [comment]
Sorry accidentally clicked it

**Comment by Kingsman44** [comment]
yes, logcat

**Comment by igorkietrz** [comment]
> yes, logcat

Is this it?
```
[Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
java.lang.IllegalStateException
	at vym.j(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
	at bjio.f(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
	at bjhh.a(:com.google.android.gms@221514044@22.15.14 (190400-441847897):10)
	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@221514044@22.15.14 (190400-441847897):12)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@221514044@22.15.14 (190400-441847897):2)
	at txh.onHandleIntent(:com.google.android.gms@221514044@22.15.14 (190400-441847897):4)
	at esa.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):3)
	at erz.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):11)
	at ccff.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by igorkietrz** [comment]
> yes, logcat

[Uploading logcat_06-05-2022_10-11-05.txt…]()
